-- CREATE TABLE Product(p_name varchar(10),p_cost int,qty int);
-- insert into Product VALUES ("pen",30,4),("pencil",10,2),("scale",50,1),("eraser",15,3);

-- Add
-- delimiter //
-- create function fadd(a int,b int)
--     returns int
--     deterministic
--     begin
--         declare c int;
--         set c=a+b;
--         return c;
--     end //
-- delimiter ;
-- select fadd(2,3);

-- Sub
-- delimiter //
-- create function fsub(a int,b int)
--     returns int
--     deterministic
--     begin
--         declare c int;
--         set c=a-b;
--         return c;
--     end //
-- delimiter ;
-- select fsub(5,3);

-- Mul
-- delimiter //
-- create function fmul(a int,b int)
--     returns int
--     deterministic
--     begin
--         declare c int;
--         set c=a*b;
--         return c;
--     end //
-- delimiter ;
-- select fmul(2,3);

-- Div
-- delimiter //
-- create function fdiv(a int,b int)
--     returns int
--     deterministic
--     begin
--         declare c int;
--         if b<>0 then
--             set c=a/b;
--             return c;
--         else
--             return -1;
--         end if;
--     end //
-- delimiter ;
-- select fdiv(10,2);

-- all
-- delimiter $$
-- create function op(a int,b int)
-- returns varchar(100)
-- deterministic
-- begin
--     declare result varchar(100);
--     SELECT concat("Sum: ",cast(fadd(a,b) as char(10)),
--     " Difference: ",cast(fsub(a,b) as char(10)),
--     " Multiplication: ",cast(fmul(a,b) as char(10)),
--     " Division: ",cast(fdiv(a,b) as char(10))
--     )  into result;
--     return result;
-- end $$
-- delimiter ;
-- select op(5,2);

-- Maximum
-- delimiter //
-- create function maximum()
--     returns int
--     deterministic
--     begin
--         declare m int;
--         select max(p_cost) into m from Product;
--         return m;
--     end //
-- delimiter ;
-- select *,maximum() as max_price from product where p_cost=maximum();